os: osx
osx_image: xcode11
language: objective-c
git:
  submodules: false
  depth: 1

before_install:
  - curl https://releases.llvm.org/8.0.0/clang+llvm-8.0.0-x86_64-apple-darwin.tar.xz --output $HOME/clang+llvm-8.0.0-x86_64-apple-darwin.tar.xz
  - tar -xzf $HOME/clang+llvm-8.0.0-x86_64-apple-darwin.tar.xz --directory $HOME
  - export PATH=$PATH:$HOME/clang+llvm-8.0.0-x86_64-apple-darwin/bin
  - llvm-config --version
  - cmake --version
  - make --version
  - brew install chargepoint/xcparse/xcparse
  - npm install junit-cli-report-viewer

script:
  - set -o pipefail && xcodebuild -project v8ios.xcodeproj -scheme TestRunner -resultBundlePath $HOME/test_results -resultBundleVersion 3 -destination platform\=iOS\ Simulator,OS\=13.0,name\=iPhone\ 11\ Pro\ Max build test | xcpretty
  - set -e && xcparse attachments $HOME/test_results.xcresult $HOME
  - set -e && find $HOME -name "*junit*.xml" -maxdepth 1 -exec npx junit-cli-report-viewer {} \;

#xcode_project: v8ios.xcodeproj
#xcode_scheme: TestRunner
#xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 11 Pro Max
